version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: discogs
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1
      interval: 5s
      timeout: 2s
      retries: 60
      start_period: 2s

  discogs-load:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: discogs
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy