[package]
name = "discogs-load"
version = "0.1.1"
authors = ["dylanbartels <dylan.j.bartels@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.0"
flate2 = "1.0.22"
anyhow = "1.0"
env_logger = "0.9.0"
postgres = "0.19.1"
structopt = "0.3.17"
indicatif = "0.16.2"
quick-xml = "0.22.0"