name: CI
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  name: Build
         run: docker-compose up -d postgres
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Run releases
        run: cargo run --bin discogs-load discogs-load/test_data/releases.xml.gz
      
      - name: Run labels
        run: cargo run --bin discogs-load discogs-load/test_data/releases.xml.gz
      
      - name: Run artists
        run: cargo run --bin discogs-load discogs-load/test_data/releases.xml.gz